CREATE TABLE "book" ("id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"title" VARCHAR(255) NOT NULL,"pages" INTEGER NOT NULL);

CREATE TABLE "author" ("id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"name" VARCHAR(255) NOT NULL);

CREATE TABLE "author_detail" ("author_id" BIGINT NOT NULL,"book_id" BIGINT NOT NULL, PRIMARY KEY("author_id","book_id"));
