micronaut:
  application:
    name: mnR2dbc
r2dbc:
  datasources:
    mydatasource:
      options:
        driver: pool
        protocol: postgres
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 'mysecretpassword'
#      schema-generate: CREATE_DROP
#      dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
#      clean-schema: true
      url: jdbc:postgresql://localhost:5432/postgres
      user: postgres
      password: 'mysecretpassword'